<?php ///[i18n:Long Text Translation]
///such as: 'Sorry, we are unable to reset password ...' => 'Sorry, we are unable to reset password for the provided email address.',

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    /**
     * Controllers
     */
    ///\vendor\yongtiger\yii2-admin\src\controllers\LogController.php
    'Successfully created.' => '创建成功。',
    'Successfully updated.' => '更新成功。',
    'Successfully deleted.' => '删除成功。',
    'Failed to delete!' => '删除失败！',
    'Deleted {0} logs.' => '共删除了 {0} 个系统操作记录。',

    /**
     * Models
     */
    ///\vendor\yongtiger\yii2-admin\src\models\Log.php
    'Route' => '路由',
    'Description' => '描述',
    'Created At' => '创建时间',
    'Updated At' => '更新时间',

    /**
     * Views
     */
    ///\vendor\yongtiger\yii2-admin\src\views\log\index.php
    'Create' => '创建',
    'Update' => '更新',
    'Batch Delete' => '批量删除',
    'Are you sure you want to delete? This is a non-recoverable operation!' => '您确定要删除吗？此操作不可恢复！',
    'Log List' => '系统操作记录列表',

    ///\vendor\yongtiger\yii2-admin\src\views\log\_search.php
    'Search' => '搜索',
    'Reset' => '重置',

    ///\vendor\yongtiger\yii2-admin\src\views\log\create.php
    'Create Log' => '创建系统操作记录',

    ///\vendor\yongtiger\yii2-admin\src\views\log\update.php
    'Update Log' => '更新系统操作记录',

    ///\vendor\yongtiger\yii2-admin\src\views\log\_form.php

    ///\vendor\yongtiger\yii2-admin\src\views\log\view.php
    'View Log' => '查看系统操作记录',
    'Are you sure you want to delete this item?' => '您确定要删除此项吗？',
    'Delete' => '删除',


    /**
     * Others
     */
    'Home' => '首页',
    'Login' => '登陆',
    'Logout' => '退出',
    'RBAC' => '权限控制',

    'Assignments' => '分配',
    'Users' => '用户列表',
    'User' => '用户',
    'Available' => '可用',
    'Assigned' => '分配',
    'Create' => '新增',
    'Update' => '更新',
    'Roles' => '角色列表',
    'Create Role' => '创建角色',
    'Name' => '名称',
    'Item Name' => '栏目名称',
    'Type' => '类型',
    'Description' => '描述',
    'Rule Name' => '规则名称',
    'Data' => '数据',
    'Update Role' => '更新角色',
    'Delete' => '删除',
    'Are you sure to delete this item?' => '确认要删除吗?',
    'ID' => 'ID',
    'Parent' => '父级',
    'Parent Name' => '父级名称',
    'Route' => '路由',
    'Username' => '用户名',
    'Update Permission' => '更新权限',
    'Permissions' => '权限列表',
    'Permission' => '权限',
    'Create Permission' => '新增权限',
    'Create Permissions' => '新增权限列表',
    'Routes' => '路由列表',
    'Create route' => '新增路由',
    'New' => '新增',
    'Generate Routes' => '生成路由',
    'Append' => '追加',
    'Create Rule' => '新增规则',
    'Rules' => '规则列表',
    'Update Rule' => '更新规则',
    'Create Menu' => '新增菜单',
    'Menus' => '菜单列表',
    'Search' => '查询',
    'Reset' => '重置',
    'Update Menu' => '更新菜单',
    'Menus' => '菜单列表',
    'Order' => '排序',
    'Class Name' => '类名',
    'Assignment' => '分配',
    'Role' => '角色',
    'Rule' => '规则',
    'Menu' => '菜单',
    'Help' => '帮助',
    'Application' => '应用',
];
